#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""clawd-mood hook — maps CLI hook events to ESP32 states via TCP.

Receives hook JSON on stdin (from Claude Code / Codex CLI) and forwards a
single NDJSON line {state, event, tool, session_id} to the daemon over a
short TCP connection. The daemon aggregates across sessions (see daemon.py).

Two event classes need care:
  * Notification (Claude Code) — only PERMISSION / ELICITATION prompts mean
    "the session is waiting for me to confirm something" → the screen's "?".
    The idle-timeout notification (sitting at the prompt ~60s) must NOT show
    as waiting, so it is ignored. Classification keys off `notification_type`
    (falling back to message text on older Claude Code that lacks it).
  * SessionEnd — carries no state; tells the daemon to drop the session from
    the concurrent count.

On SessionStart, spawns the daemon detached if not already running. Pure
stdlib (no third-party deps) so uv run is fast (~80-200ms cached).
"""

import json
import socket
import subprocess
import sys
import tempfile
from pathlib import Path

PORTFILE = Path(tempfile.gettempdir()) / "clawd-mood.port"
LOGFILE = Path(tempfile.gettempdir()) / "clawd-mood-daemon.log"

# Events with a fixed 1:1 state. Notification is handled separately because its
# meaning depends on notification_type (see classify_notification).
EVENT_TO_STATE = {
    "SessionStart":       "idle",
    "UserPromptSubmit":   "working",     # was thinking; thinking folded into working
    "PreToolUse":         "working",
    "PostToolUse":        "working",
    "PostToolUseFailure": "error",       # Claude Code only
    "Stop":               "done",
    "PermissionRequest":  "waiting",     # Codex only (Claude Code uses Notification)
    "PreCompact":         "working",     # compact in progress -> running (both CLIs)
    "PostCompact":        "idle",        # compact finished -> idle (both CLIs)
}
# SubagentStart / SubagentStop are deliberately NOT mapped:
#   * Redundant for a real subagent — it is launched via the Task tool, whose
#     PreToolUse/PostToolUse already mark the session "working".
#   * The away_summary / recap is generated by an INTERNAL subagent that fires
#     SubagentStop with NO preceding Task PreToolUse, when the user is idle/away.
#     Mapping it to "working" flipped an idle session back to working and left it
#     stuck (no Stop follows a recap). Ignoring Subagent* kills that false flip
#     while losing nothing for real subagents.

# Notification types (Claude Code) we care about:
#   permission_prompt / elicitation_dialog -> "waiting"  (the screen's "?")
#   idle_prompt                            -> "idle"      (prompt sat idle ~60s)
# auth_success / elicitation_complete / elicitation_response -> ignored.
#
# idle_prompt is our best-effort recovery for INTERRUPTS: Claude Code fires NO
# hook when the user hits Esc, so an interrupted turn would otherwise stay stuck
# at working/thinking. ~60s after the turn ends (or is interrupted) the prompt
# goes idle and fires idle_prompt → we reset the session to idle. It does NOT
# fire while a long tool/generation is actually running, so it won't false-drop
# a genuinely busy session.
WAITING_NOTIFICATION_TYPES = {"permission_prompt", "elicitation_dialog"}
IDLE_NOTIFICATION_TYPES = {"idle_prompt"}


def classify_notification(payload: dict) -> str | None:
    """A Claude Code Notification → "waiting" (confirmation), "idle" (idle
    prompt), or None (ignored)."""
    ntype = payload.get("notification_type")
    if ntype is not None:
        if ntype in WAITING_NOTIFICATION_TYPES:
            return "waiting"
        if ntype in IDLE_NOTIFICATION_TYPES:
            return "idle"
        return None
    # Older Claude Code without notification_type: infer from the message text.
    msg = (payload.get("message") or "").lower()
    if "permission" in msg or msg.startswith("allow ") or "needs your" in msg:
        return "waiting"
    if "waiting for your input" in msg:
        return "idle"
    return None


def classify(payload: dict) -> dict | None:
    """Map a hook payload to the NDJSON dict to send to the daemon, or None to
    send nothing. SessionEnd returns a stateless drop message."""
    event = payload.get("hook_event_name", "")
    session_id = payload.get("session_id", "")
    cwd = payload.get("cwd", "")
    if event == "SessionEnd":
        return {"event": event, "session_id": session_id, "cwd": cwd}
    if event == "Notification":
        state = classify_notification(payload)
    else:
        state = EVENT_TO_STATE.get(event)
    if state is None:
        return None
    return {
        "state": state,
        "event": event,
        "tool": payload.get("tool_name", ""),
        "session_id": session_id,
        "cwd": cwd,
    }


def read_portfile() -> int | None:
    try:
        return int(PORTFILE.read_text().strip())
    except (OSError, ValueError):
        return None


def probe_daemon() -> bool:
    port = read_portfile()
    if port is None:
        return False
    try:
        with socket.create_connection(("127.0.0.1", port), timeout=0.1):
            return True
    except OSError:
        return False


def ensure_daemon_running() -> None:
    if probe_daemon():
        return
    daemon_path = Path(__file__).parent / "daemon.py"
    log_fh = open(LOGFILE, "a")
    if sys.platform == "win32":
        CREATE_NO_WINDOW = 0x08000000
        DETACHED_PROCESS = 0x00000008
        subprocess.Popen(
            ["uv", "run", str(daemon_path)],
            stdout=log_fh,
            stderr=log_fh,
            stdin=subprocess.DEVNULL,
            creationflags=DETACHED_PROCESS | CREATE_NO_WINDOW,
            close_fds=True,
        )
    else:
        subprocess.Popen(
            [str(daemon_path)],
            stdout=log_fh,
            stderr=log_fh,
            stdin=subprocess.DEVNULL,
            start_new_session=True,
            close_fds=True,
        )


def main() -> None:
    try:
        payload = json.loads(sys.stdin.read())
    except json.JSONDecodeError:
        return

    if payload.get("hook_event_name") == "SessionStart":
        ensure_daemon_running()

    msg = classify(payload)
    if msg is None:
        return  # event carries no state for us (e.g. idle Notification)
    line = json.dumps(msg) + "\n"

    port = read_portfile()
    if port is None:
        return  # daemon still warming up; next event will catch up
    try:
        with socket.create_connection(("127.0.0.1", port), timeout=0.3) as s:
            s.sendall(line.encode())
    except OSError:
        pass  # daemon not responding; silently drop


if __name__ == "__main__":
    main()
